name: Auto Update Clash Proxies

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点执行一次（北京时间早上 8 点）
  workflow_dispatch:      # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python gen.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add *.yaml
          git commit -m "Auto update proxies" || echo "Nothing to commit"
          git remote set-url origin https://mingko3:${{ secrets.GH_TOKEN }}@github.com/mingko3/socks5-clash-proxy.git
          git push
