name: Update SOCKS5 Proxies and Generate Clash Config

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script to generate proxy.yaml
        run: python generate.py

      - name: Setup Git credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://mingko3:${{ secrets.GH_TOKEN }}@github.com/mingko3/socks5-clash-proxy.git

      - name: Commit and push changes
        run: |
          git add proxy.yaml
          git commit -m "Auto update proxies" || echo "Nothing to commit"
          git push
